name: "Build GHA"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    env:
      TAG: ${{ format('{0}.{1}', '0.0.999', github.run_number) }}
    steps:
      - uses: actions/checkout@v3.2.0
      - uses: microsoft/setup-msbuild@v1.1
      - uses: actions/setup-dotnet@v3

      - name: ⬇️ Setup YAK
        run: |
          curl https://files.mcneel.com/yak/tools/latest/yak.exe -o yak.exe
          Split-Path (Get-ChildItem "./" yak.exe -Recurse).fullname | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: 🦗 Build GH Plugin
        run: |
          dotnet build -c Release /p:Version=$env:TAG

      - name: ✨Create plugin manifest
        run: |
          yak spec
          Add-Content manifest.yml "icon: Resources/SizeAnalyzerIcon.png"
        working-directory: GH_SizeAnalyzer/bin/Release

      - name: 🚧 Build YAK package
        run: yak build
        working-directory: GH_SizeAnalyzer/bin/Release

      - name: 📦 Archive yak file
        uses: actions/upload-artifact@v3
        with:
          name: GH_SizeAnalyzer-${{ env.TAG }}.yak
          path: "./GH_SizeAnalyzer/bin/Release/*.yak"
          retention-days: 2
