name: "Build GHA"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    env:
      TAG: ${{ format('{0}.{1}', '0.0.999', github.run_number) }}
    steps:
      - uses: actions/checkout@v3.2.0
      - uses: paramdigma/setup-yak@main

      - name: 🦗 Build GH Plugin
        run: dotnet build -c Release /p:Version=$env:TAG

      - name: ✨Create plugin manifest
        run: |
          yak spec
          Add-Content manifest.yml "icon: Resources/SizeAnalyzerIcon.png"
        working-directory: GH_SizeAnalyzer/bin/Release

      - name: 🚧 Build YAK package
        run: yak build
        working-directory: GH_SizeAnalyzer/bin/Release

      - name: 📦 Archive yak file
        uses: actions/upload-artifact@v3
        with:
          name: GH_SizeAnalyzer-${{ env.TAG }}.yak
          path: "./GH_SizeAnalyzer/bin/Release/*.yak"
          retention-days: 2
