name: "CI"

on:
  push:
    branches:
      - main
      - ci

jobs:
  build:
    runs-on: windows-latest
    env:
      YAK_TOKEN: ${{ secrets.YAK_TOKEN }}
      BUILD_NUM: ${{ github.run_id }}
    steps:
      - uses: actions/checkout@v2
      - uses: microsoft/setup-msbuild@v1.1
      - uses: actions/setup-dotnet@v3
      - name: Build app for release
        run: |
          $tag = "2.0.0"
          dotnet build /p:AssemblyVersionNumber=$env:tag /p:AssemblyInformationalVersion=$env:tag /p:Version=$env:tag
      # Runs a set of commands using the runners shell
      - name: Download yak
        run: |
          curl https://files.mcneel.com/yak/tools/latest/yak.exe -o yak.exe
          cd ./GH_SizeAnalyzer/bin/Debug
          ../../../yak spec
      - name: Build Yak
        run: |
          cd ./GH_SizeAnalyzer/bin/Debug
          ../../../yak build
