name: "Deploy to YAK"

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3.2.0
      - uses: paramdigma/setup-yak@1.0.0
        with:
          token: ${{ secrets.YAK_TOKEN }}

      - name: 🦗 Build GH Plugin
        run: |
          dotnet build -c Release /p:Version=${{ github.ref_name }}

      - name: ✨Create plugin manifest
        run: |
          yak spec
          Add-Content manifest.yml "icon: Resources/SizeAnalyzerIcon.png"
        working-directory: GH_SizeAnalyzer/bin/Release

      - name: 🚧 Build YAK package
        run: yak build
        working-directory: GH_SizeAnalyzer/bin/Release

      - name: 🚀 Deploy to Rhino package manager
        run: |
          $env:YAK_FILE = (Get-ChildItem "./" *.yak -Recurse).fullname
          yak push $env:YAK_FILE
        working-directory: GH_SizeAnalyzer/bin/Release
